# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubDYLW8GjSkWn6jFiJ5M0V7qWQqVcJWJ
"""

import pandas as pd
import numpy as np

# Define industries and years
industries = ['Energy', 'Transportation', 'Manufacturing', 'Agriculture', 'Construction', 'Mining']
years = np.arange(2020, 2025)

# Generate sample data
data = {
    'Industry': np.random.choice(industries, 100),
    'Year': np.random.choice(years, 100),
    'Emissions': np.random.uniform(2000, 6000, 100)
}

df = pd.DataFrame(data)

# Save to CSV for inspection
df.to_csv('sample_emissions_data.csv', index=False)

print(df.head())